
const amiquusDomain = "https://www.amiquus.com";
const APP_NAME = "Amiquus";
const SUPPORT_EMAIL = "support@amiquus.com"; 
const DASHBOARD_URL = `${amiquusDomain}/dashboard`; 
const SENDER_EMAIL = "info@amiquus.com";

// Card testing prevention: Do not retry failures like DO_NOT_HONOR, STOLEN_CARD, LOST_CARD, PICKUP_CARD, FRAUDULENT, AUTHENTICATION_FAILURE.

const RETRIABLE_ERRORS = [
    'AUTHENTICATION_REQUIRED',
    'AUTHENTICATION_TIMEOUT',
    'CARD_NOT_ACTIVATED',
    'CARD_VELOCITY_EXCEEDED',
    'CUSTOMER_CANCELLED',
    'EXPIRED_CARD',
    'INCORRECT_CVC',
    'INCORRECT_NUMBER',
    'INSUFFICIENT_FUNDS',
    'INVALID_ACCOUNT',
    'INVALID_AMOUNT',
    'INVALID_CARD_NUMBER',
    'INVALID_CARD_OWNER',
    "INVALID_CVC",
    'INVALID_EXPIRY_YEAR',
    'INVALID_PIN',
    'INVALID_REQUEST',
    'INVALID_UPI_ID',
    'LIMIT_EXCEEDED',
    'LIVE_MODE_TEST_CARD',
    'MANDATE_INVALID',
    'MANDATE_REQUIRED',
    'PAYMENT_METHOD_PROVIDER_DECLINED',
    'PAYMENT_METHOD_UNSUPPORTED',
    'REENTER_TRANSACTION',
    'REVOCATION_OF_AUTHORIZATION',
    'TRANSACTION_NOT_ALLOWED',
    'TRANSACTION_NOT_APPROVED'
];


export {APP_NAME, SUPPORT_EMAIL, DASHBOARD_URL, SENDER_EMAIL, RETRIABLE_ERRORS};